theme: jekyll-theme-minimal
title: My Portfolio
description: Welcoem to my portfolio! My name is Kristina, and I am a first year at Rutgers University majoring in computer science. Here you will find projects that I have worked on.
